DapperDemo/Models/Company.cs
using System.ComponentModel.DataAnnotations;

namespace DapperDemo.Models
{
    public class Company
    {
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }

        public List<Employee>? Employees { get; set; }




        public Company()
        {
            Employees = new List<Employee>();
        }
    }
}

DapperDemo/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DapperDemo.Data;
using DapperDemo.Models;
using DapperDemo.Repository;

namespace DapperDemo.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ICompanyRepository _companyRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IBonusRepository _bonusRepository;
        private readonly IDapperSprocRepo _dapperSprocRepo;

        [BindProperty]
        public Company Company { get; set; }

        public CompaniesController(ICompanyRepository companyRepository, IEmployeeRepository employeeRepository, IBonusRepository bonusRepository, IDapperSprocRepo dapperSprocRepo)
        {
            _companyRepository = companyRepository;
            _employeeRepository = employeeRepository;
            _bonusRepository = bonusRepository;
            _dapperSprocRepo = dapperSprocRepo;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            // return View(_companyRepository.GetAll());
            return View(_dapperSprocRepo.List<Company>("usp_GetALLCompany"));
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = _bonusRepository.GetCompanyWithAddresses(id.GetValueOrDefault());
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Create")]
        public async Task<IActionResult> CreatePOST()
        {
            if (ModelState.IsValid)
            {
                _companyRepository.Add(Company);
                return RedirectToAction(nameof(Index));
            }
            return View(Company);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var company = _companyRepository.Find(id.GetValueOrDefault());
            var company = _dapperSprocRepo.Single<Company>("usp_GetCompany", new
            {
                CompanyId = id.GetValueOrDefault()
            });
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CompanyId,Name,Address,City,State,PostalCode")] Company company)
        {
            if (id != company.CompanyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _companyRepository.Update(company);
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _companyRepository.Remove(id.GetValueOrDefault());
            return RedirectToAction(nameof(Index));
        }
    }
}

DapperDemo/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DapperDemo.Data;
using DapperDemo.Models;
using DapperDemo.Repository;

namespace DapperDemo.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ICompanyRepository _companyRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IBonusRepository _bonusRepository;

        [BindProperty]
        public Employee Employee { get; set; }

        public EmployeesController(ICompanyRepository companyRepository, IEmployeeRepository employeeRepository, IBonusRepository bonusRepository)
        {
            _companyRepository = companyRepository;
            _employeeRepository = employeeRepository;
            _bonusRepository = bonusRepository;
        }

        // GET: Employees
        public async Task<IActionResult> Index(int companyId=0)
        {
            List<Employee> employees = _bonusRepository.GetEmployeWithCompany(companyId);
            return View(employees);
        }

        //// GET: Employees/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var company = _companyRepository.Find(id.GetValueOrDefault());
        //    if (company == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(company);
        //}

        // GET: Employees/Create
        public IActionResult Create()
        {
            IEnumerable<SelectListItem> companyList = _companyRepository.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.CompanyId.ToString()
            });

            ViewBag.CompanyList = companyList;
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Create")]
        public async Task<IActionResult> CreatePOST()
        {
            if (ModelState.IsValid)
            {
                await _employeeRepository.AddAsync(Employee);
                return RedirectToAction(nameof(Index));
            }
            return View(Employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Employee = _employeeRepository.Find(id.GetValueOrDefault());

            IEnumerable<SelectListItem> companyList = _companyRepository.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.CompanyId.ToString()
            });

            ViewBag.CompanyList = companyList;

            if (Employee == null)
            {
                return NotFound();
            }
            return View(Employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            if (id != Employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _employeeRepository.Update(Employee);
                return RedirectToAction(nameof(Index));
            }
            return View(Employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _employeeRepository.Remove(id.GetValueOrDefault());
            return RedirectToAction(nameof(Index));
        }
    }
}

DapperDemo/Views/Companies/Create.cshtml
@model DapperDemo.Models.Company

<h1>Create Company</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-6">
                    <input type="submit" value="Create" class="btn btn-primary form-control" />

                </div>
                <div class="col-6">
                    <a asp-action="Index" class="btn btn-warning form-control">Back to List</a>

                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DapperDemo/Views/Companies/Details.cshtml
@model DapperDemo.Models.Company

    <div class="container">
        <div class="row">
            <div class="col-9">
                <h1>Company Details</h1>

            </div>
            <div class="col-3">
<a asp-action="Index" asp-controller="Companies" class="btn btn-warning">Back to Companies</a>
            </div>
        </div>
        <hr />

        <div class="row p-1">
            <div class="col-3">
                Name
            </div>
            <div class="col-9">
                <input asp-for="Name" class="form-control" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-3">
                Address
            </div>
            <div class="col-9">
                <input asp-for="Address" class="form-control" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-3">
                City
            </div>
            <div class="col-9">
                <input asp-for="City" class="form-control" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-3">
                State
            </div>
            <div class="col-9">
                <input asp-for="State" class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                Postal Code
            </div>
            <div class="col-9">
                <input asp-for="PostalCode" class="form-control" />
            </div>
        </div>

    </div>
<hr />
<div class="container pt-2">
    <div class="row py-2">
        <h3>Employee Details</h3>
    </div>
    <div class="row">
        @if (Model.Employees.Count() > 0)
        {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Employees.FirstOrDefault().Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Employees.FirstOrDefault().Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Employees.FirstOrDefault().Phone)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Employees.FirstOrDefault().Title)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Employees)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Phone)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-controller="Employees" asp-route-id="@item.EmployeeId" class="btn btn-info">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        }
        else
        {
            <p>No employee exists...</p>
        }
    </div>
</div>

DapperDemo/Views/Companies/Edit.cshtml
@model DapperDemo.Models.Company

@{
    ViewData["Title"] = "Edit";
}

    <h1>Edit Company</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CompanyId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-6">
                    <input type="submit" value="Save" class="btn btn-primary form-control" />

                </div>
                <div class="col-6">
                    <a asp-action="Index" class="btn btn-warning form-control">Back to List</a>

                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DapperDemo/Views/Companies/Index.cshtml
@model IEnumerable<DapperDemo.Models.Company>

<h1>Company Management</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Add Company</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostalCode)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostalCode)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CompanyId" class="btn btn-info">Edit</a>
                <a asp-action="Details" asp-route-id="@item.CompanyId" class="btn btn-success">Details</a>
                <a asp-action="Delete" asp-route-id="@item.CompanyId" class="btn btn-danger">Delete</a>
            </td>
            <td>
                <a asp-action="Index" asp-controller="Employees" asp-route-companyId="@item.CompanyId" class="btn btn-primary">Manage Employees</a>
            </td>
        </tr>
}
    </tbody>
</table>